- name: apache
  hosts: Group_01
  become: true
  tasks:
    - name:  install apache
      apt: name=apache2 state=present
    - name: start apache2
      service:
          name: apache2
          state: started

#Create a playbook that installs a specific package on a group of remote servers
