- name: Update apt cache
  apt:
    update_cache: yes
- name: Install MySQL packages
  apt:
    name: ['mysql-server', 'mysql-client']
    state: present

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes
